apiVersion: v1
kind: Pod
metadata:
  name: application2
  namespace: sub-team2
  environment: dev
spec:
  containers:
  - name: busybox
    image: busybox
    command: [sleep, Infinity]
    imagePullPolicy: IfNotPresent
