apiVersion: v1
kind: Pod
metadata:
  name: application1
  namespace: sub-team1
  environment: dev
spec:
  containers:
  - name: busybox
    image: busybox
    command: [sleep, Infinity]
    imagePullPolicy: IfNotPresent
